
services:
  web:
    container_name: cypher
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3660:3000"
    env_file:
      - .env
    restart: unless-stopped
